---
- name: "Setup systemd service"
  template:
    src: gitea.service.j2
    dest: /lib/systemd/system/gitea.service
    owner: root
    group: root
    mode: 0644
  notify:
    - "Reload systemd"
    - "Restart gitea"

# systemd to be reloaded the first time because it is the only way Systemd is going to be aware of the new unit file.
- name: "Reload systemd"
  systemd:
    daemon_reload: true
